#!/bin/env bash
set -e
# g++ code.cpp -o code
# g++ gen.cpp -o gen
# g++ brute.cpp -o brute
python3 $1 gen > /dev/null
for((i = 1; ; ++i)); do
    python3 $1 gen $i > input_file
    python3 $1 < input_file > myAnswer
    # python3 $1 check < myAnswer
    python3 $1 brute < input_file > correctAnswer
    # python3 $1 check < correctAnswer
    diff -Z myAnswer correctAnswer > /dev/null || break
    echo "Passed test: "  $i
done
echo "WA on the following test:"
cat input_file
echo "Your answer is:"
cat myAnswer
echo "Correct answer is:"
cat correctAnswer